from supabase import create_client, Client
import os

SUPABASE_URL= "https://tnerctbwcysfezucsaow.supabase.co/"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZXJjdGJ3Y3lzZmV6dWNzYW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzY2NjQsImV4cCI6MjA3Nzc1MjY2NH0.uUyS997YdiMIuA2SKFhwg4_DiFg1M0HetqbBZwVCnJc"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
